### ISSUE TITLE
Why python instead of C# implementation?

### ISSUE THREAD

**Issue by eintopf** [codeserk/wakatime-unity#12]
Hi,

I use the wakatime unity plugin for some months now. It is working like it should, but what is really annoying are the upcoming python windows + the ultra slow speed of python in general. Sometimes - when switching branches the CPU ramps up to 100% only due to several python instances.

Since wakatime is based on an REST API, why it is not talken to via a C# HTTP client?

Would appreciate an answer :)

Best regards
eintopf

**Comment by alanhamlett** [comment]
> why it is not talken to via a C# HTTP client?

To prevent duplicating logic, we implemented the language detection, project detection, offline caching, and API communication code in a common Python module called [wakatime cli](https://github.com/wakatime/wakatime).

**Comment by eintopf** [comment]
Ok got that, wasn't aware that there was going on so much under the hood, but it makes sense. What do you think of a port to Golang, which would be alot faster for sure.

**Comment by alanhamlett** [comment]
I've considered implementing the cli in Go or Rust, but the language detection depends on a Python library [pygments](http://pygments.org/). Porting pygments into Go would be a huge task.

**Comment by alanhamlett** [comment]
Another option is using [Nuitka](http://nuitka.net/) to compile the Python code into a standalone binary that doesn't need Python to run:

```
nuitka \
  --standalone \
  --recurse-all \
  --recurse-directory=wakatime/packages/ \
  --recurse-directory=wakatime/packages/urllib3/packages/ \
  --recurse-directory=wakatime/packages/urllib3/ \
  wakatime/cli.py
```

That produces `wakatime.exe` at 41.6MB and runs without Python.

**Comment by codeserk** [comment]
Hello!
I've made some improvements that makes the fact that is using python not so bad, but it's still pretty bad (especially when installing!)

I think in most situations is better to check other implementations that work with a native client in C#
https://wakatime.com/unity
