### ISSUE TITLE
Importing small assets causes a computer crash for large project

### ISSUE THREAD

**Issue by ClintonCollins** [codeserk/wakatime-unity#14]
When unity imports a lot of small assets wakatime spawns up dozens of python processes using 100% CPU on my i7-6800K until my computer runs out of memory and crashes (48GB of RAM). Tested a few times and removing the wakatime directory fixes the insane resource usage and the import is much faster as well.

**Comment by codeserk** [comment]
Hello!
Sorry for the (very) late reply! I didn't pay much attention to this repository :D 
You were right, it was going crazy even with really small amount of changes. I've introduced some changes to prevent that:
- I've wrapped requests into Tasks, so they run in the background
- I've limited the number of concurrent requests (5 by default, editable in the window)

But the big problem is still python: a single request can take more than 5 secs :/ 
https://wakatime.com/unity
It's probably better to check other implementations that have native C# client
