### ISSUE TITLE
Installation instructions should be clarified to remove tests subfolder from client

### ISSUE THREAD

**Issue by ahokinson** [codeserk/wakatime-unity#20]
While updating the submodules to grab the latest client, git pulled in a tests subfolder which won't compile due to namespace issues. It's clear from the code why that is...

```using WakaTime.Forms;
using static Math.Foo;
using Task = Fart.Threading.Tasks.Task;
using static Proper.Bar;
```

Since it is test code from the submodule, it can be safely removed and the plugin works as intended.

I'm not sure how to make a git submodule ignore a specific folder, but perhaps your instructions could indicate that the tests folder should be removed before adding to Unity?

**Comment by codeserk** [comment]
Good suggestion, I've addd a line in the `README` for this
