### ISSUE TITLE
Error when the unity project folder filename contains a space

### ISSUE THREAD

**Issue by Dennis960** [codeserk/wakatime-unity#23]
Wakatime integration into a Unity Project doesn't work when the projectfolder has a space in its name (Example "Hopping Adventure" doesn't work, "Hopping_Adventure" works)
Quickfix for users: replace or remove the spaces

Wakatime Error: usage: wakatime [-h] [--entity FILE] [--key KEY] [--write] [--plugin PLUGIN]
                [--time time] [--lineno LINENO] [--cursorpos CURSORPOS]
                [--entity-type ENTITY_TYPE] [--proxy PROXY] [--no-ssl-verify]
                [--project PROJECT] [--alternate-project ALTERNATE_PROJECT]
                [--language LANGUAGE] [--hostname HOSTNAME]
                [--disable-offline] [--hide-filenames] [--exclude EXCLUDE]
                [--include INCLUDE] [--include-only-with-project-file]
                [--extra-heartbeats] [--log-file LOG_FILE] [--api-url API_URL]
                [--timeout TIMEOUT] [--config CONFIG] [--verbose] [--version]
wakatime: error: unrecognized arguments: Adventure _<-- this is the filename after the space_

UnityEngine.Debug:LogError(Object)
WakaTime.ClientManager:HeartBeat(String, String, Boolean) (at Assets/Editor/WakaTime/ClientManager.cs:69)
WakaTime.Main:RequestSendFile(String, Boolean) (at Assets/Editor/WakaTime/Main.cs:164)
WakaTime.Main:OnSceneChanged(String) (at Assets/Editor/WakaTime/Main.cs:151)
WakaTime.SceneDirtyChecker:OnPostProcessModifications(UndoPropertyModification[]) (at Assets/Editor/WakaTime/SceneDirtyChecker.cs:26)
UnityEditor.Undo:InvokePostprocessModifications(UndoPropertyModification[])`

**Comment by codeserk** [comment]
Hello,
Good catch! I think there's an easy fix for this, I'll send you a PR soon to check if it solves the problem for you too :)
