### ISSUE TITLE
ability to log for all projects without being added to Assets folder

### ISSUE THREAD

**Issue by alanhamlett** [codeserk/wakatime-unity#4]
Is it possible to install the plugin for all Unity projects without needing to add to `Assets`?

**Comment by igarcez** [comment]
maybe it is not possible, but you can add the package to the import package context menu moving it's files here:
Windows: C:\Program Files\Unity\Editor\Standard Packages
OS X: /Applications/Unity/Standard Packages

this will make a little quicker to import it to your new project
