### ISSUE TITLE
All errors must be resolved before window will pop up prompting for API key

### ISSUE THREAD

**Issue by xRJx** [codeserk/wakatime-unity#6]
It confused me when I first tried installing it. It'd probably be a good idea to make a note of that or somehow make it so it doesn't do that.

**Comment by nickmccurdy** [comment]
I'm not sure if this is what you experienced, but after installing it I immediately got a popup that I couldn't continue without filling my API key, my only options were to close the window and then displayed the API key setup window or to try to continue but the popup would continue appearing. Only after canceling and filling my API key did it work, and I did have console errors.

**Comment by codeserk** [comment]
I've made a small change: 
The plugin will be disabled regardless of the button you press, that way we prevent weird loops because the plugin is enabled while no API key is present.
Downside is that we need to remember to re-enable the plugin (checking that checkbox :D )
